### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by darkHarry** [diveshlunker/whatsall#2]
Hey @diveshlunker !

Awesome Automation. It would be great if it could send Custom Messages for each Number. Are there any plans for that ?

**Comment by diveshlunker** [comment]
Hey @darkHarry 
I will be adding that feature for sure but it might take some and Thank you:)

**Comment by darkHarry** [comment]
Cool. Would love to work on it too.

**Comment by diveshlunker** [comment]
Your suggested feature is added, I will be updating the documentation soon.
Closing this issue.
